version: '3.8'

services:
  # Reacharr Local Agent Backend
  reacharr-agent:
    image: ghcr.io/reacharrpascal/reacharr-localagent:latest
    container_name: reacharr-agent
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "3000:3000"
    networks:
      - reacharr-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); http.get('http://localhost:3000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Configuration Web UI
  reacharr-config-ui:
    image: ghcr.io/reacharrpascal/reacharr-configui:latest
    container_name: reacharr-config-ui
    environment:
      - REACT_APP_AGENT_API_URL=http://localhost:3000
    ports:
      - "3001:3000"
    networks:
      - reacharr-network
    restart: unless-stopped
    depends_on:
      reacharr-agent:
        condition: service_healthy

networks:
  reacharr-network:
    driver: bridge

volumes:
  reacharr_data: 